### ISSUE TITLE
[BUG] lua bit32 module is not available in turris omnia

### ISSUE THREAD

**Issue by dim-geo** [Fail-Safe/sqm-autorate#31]
**Describe the bug**
lua bit32 module is not available in turris omnia

**To Reproduce**
Try to run the script in latest stable turris omnia

**Expected behavior**
It should be able to run

**Screenshots**
```
lua: module 'bit32' not found:
        no field package.preload['bit32']
        no file '/root/.luarocks/share/lua/5.1/bit32.lua'
        no file '/root/.luarocks/share/lua/5.1/bit32/init.lua'
        no file '/usr/share/lua/5.1/bit32.lua'
        no file './bit32.so'
```

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release:
```
NAME="TurrisOS"
VERSION="5.3.2"
ID="turrisos"
ID_LIKE="lede openwrt"
PRETTY_NAME="TurrisOS 5.3.2"
VERSION_ID="5.3.2"
HOME_URL="https://www.turris.cz/"
BUG_URL="https://gitlab.nic.cz/groups/turris/-/issues/"
SUPPORT_URL="https://www.turris.cz/support/"
BUILD_ID="r11388+90-f14bc5cf56"
OPENWRT_BOARD="mvebu/cortexa9"
OPENWRT_ARCH="arm_cortex-a9_vfpv3-d16"
OPENWRT_TAINTS="busybox"
OPENWRT_DEVICE_MANUFACTURER="CZ.NIC"
OPENWRT_DEVICE_MANUFACTURER_URL="https://www.turris.cz/"
OPENWRT_DEVICE_PRODUCT="Turris Omnia"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="TurrisOS 5.3.2 f14bc5cf5635edbb3ab2e29c14a260e2640e588f"

```
**Additional context**
Can we use the module bitop instead, which is available?
http://bitop.luajit.org/

**Comment by Lochnair** [comment]
Pushed a possibly fix for bit32 to my own branch: https://github.com/Fail-Safe/sqm-autorate/commit/5a916f705711753032a70416bec3b0fb6be26a0f

Please test with that and see if that helps.

**Comment by Fail-Safe** [comment]
@dim-geo  Can you confirm if this is fixed for you on the `testing/lua-threads` branch?

**Comment by dim-geo** [comment]
This part needs fixing as well:

```
    local threads = {
        receiver = lanes.gen("*", {
            required = {"bit32", "posix.sys.socket", "posix.time", "vstruct"}
        }, ts_ping_receiver)(packet_id, reflector_type),
        baseliner = lanes.gen("*", {
            required = {"bit32", "posix", "posix.time"}
        }, baseline_calculator)(),
        regulator = lanes.gen("*", {
            required = {"bit32", "posix", "posix.time"}
        }, ratecontrol)(),
        pinger = lanes.gen("*", {
            required = {"bit32", "posix.sys.socket", "posix.time", "vstruct"}
        }, ts_ping_sender)(reflector_type, packet_id, tick_duration)
    }
```

**Comment by Fail-Safe** [comment]
> This part needs fixing as well:
> 
> ```
>     local threads = {
>         receiver = lanes.gen("*", {
>             required = {"bit32", "posix.sys.socket", "posix.time", "vstruct"}
>         }, ts_ping_receiver)(packet_id, reflector_type),
>         baseliner = lanes.gen("*", {
>             required = {"bit32", "posix", "posix.time"}
>         }, baseline_calculator)(),
>         regulator = lanes.gen("*", {
>             required = {"bit32", "posix", "posix.time"}
>         }, ratecontrol)(),
>         pinger = lanes.gen("*", {
>             required = {"bit32", "posix.sys.socket", "posix.time", "vstruct"}
>         }, ts_ping_sender)(reflector_type, packet_id, tick_duration)
>     }
> ```

This should now be resolved. I merged an update for this into the lua-threads branch. Can you please install the latest and test again for us?
