### ISSUE TITLE
[FEATURE] Include some kind of version number

### ISSUE THREAD

**Issue by richb-hanover** [Fail-Safe/sqm-autorate#33]
As we move forward, we are increasingly going to be asking "What version are you using?" 

At the moment, there's no good answer... ("Hmmm... I think it's the one that I downloaded after we fixed X...")

I don't know a good solution for this, but it would be slick to offer one of these:
- cat a file that has a "version" string/property
- `sqm-autorate.lua --version`
- or something else....

Thanks.

**Comment by Fail-Safe** [comment]
This is a great point and I actually made a very last-minute add to work a version into the code. But I didn't provide a clean way to expose it via CLI yet.

Reference: 
https://github.com/Fail-Safe/sqm-autorate/commit/c663b2fa57b9adf1d45762b3c079d0d600eed349

I will work on a true arg-based way to expose this because I fully agree that it is going to be critical for ongoing support.

**Comment by Fail-Safe** [comment]
Is everyone good with sticking to SemVer convention for versioning? https://semver.org/

**Comment by richb-hanover** [comment]
A thought... Move the:

> local _VERSION...

line into the first few lines, so that the `getstats.sh` script could issue `head /usr/lib/sqm-autorate/sqm-autorate.lua` to display its version number

**Comment by richb-hanover** [comment]
And Yes to SemVer.

**Comment by Fail-Safe** [comment]
> A thought... Move the:
> 
> > local _VERSION...
> 
> line into the first few lines, so that the `getstats.sh` script could issue `head /usr/lib/sqm-autorate/sqm-autorate.lua` to display its version number

Should we just scrape it out in the short-term like so?
```bash
root@OpenWrt:~# grep -e "_VERSION" /usr/lib/sqm-autorate/sqm-autorate.lua | cut -d" " -f4 | sed 's/"//g'
0.0.1b1
```

**Comment by Fail-Safe** [comment]
Regardless, I am presently working on getting argparse into the script so I can return this version and any other future args we might want to handle.

**Comment by Fail-Safe** [comment]
@richb-hanover How does this look to you?

```bash
root@OpenWrt:~/sqm-autorate# /usr/lib/sqm-autorate/sqm-autorate.lua -h
Usage: sqm-autorate.lua [-v] [-h]

CAKE with Adaptive Bandwidth - 'autorate'

Options:
   -v, --version         Displays the SQM Autorate version.
   -h, --help            Show this help message and exit.

For more info, please visit: https://github.com/Fail-Safe/sqm-autorate
root@OpenWrt:~/sqm-autorate# /usr/lib/sqm-autorate/sqm-autorate.lua -v
0.0.1b1
root@OpenWrt:~/sqm-autorate# /usr/lib/sqm-autorate/sqm-autorate.lua --version
0.0.1b1
```

**Comment by Fail-Safe** [comment]
I need to update this idea since lua-argparse is not available for OpenWrt 19.07.

**Comment by richb-hanover** [comment]
This looks perfect. (I can live without 19.07 in the first round of testing...)

**Comment by Fail-Safe** [comment]
@richb-hanover I just updated the code to take advantage of argparse if it is available, and if not, no error and the code just rolls on without it. The end-user will just lose some of the niceties of any arguments/options we might add down the road.

**Comment by richb-hanover** [comment]
Perfect.

**Comment by richb-hanover** [comment]
PS Inching closer to 2.0X or maybe even 2.5X :-)
