### ISSUE TITLE
[BUG] sqm-autorate service fails to start after reboot

### ISSUE THREAD

**Issue by dveith** [Fail-Safe/sqm-autorate#45]
**Script Version**
sqm-autorate.lua v0.0.1b4

**Describe the bug**
When sqm-autorate is configured as a service it fails to start after a reboot. But subsequently manually starting the service is successful. 

**Screenshots**

![image2](https://user-images.githubusercontent.com/2898024/147893134-a5bfe2bf-7fd6-46d1-9d62-9be95aa75e12.jpg)

Model: Ubiquiti EdgeRouter X
Architecture: MediaTek MT7621 ver:1 eco:3
Firmware Version: OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d
Kernel Version: 5.4.154

**Comment by Fail-Safe** [comment]
Could you please update to the latest `testing/lua-threads` code and see if this has resolved this issue for you?

**Comment by dveith** [comment]
This is no longer having this issue on sqm-autorate.lua v0.0.1b7.  Thank you.
