### ISSUE TITLE
[BUG] sqm-autorate doesn't restart after reboot

### ISSUE THREAD

**Issue by richb-hanover** [Fail-Safe/sqm-autorate#51]
**Script Version** 0.0.1b5 version of **testing/lua-threads**

**Describe the bug**
After rebooting the router, the `sqm-autorate` service doesn't seem to restart.

**To Reproduce**
1. Reboot the router
2. Examine `top`. No sign of `sqm-autorate.lua`
3. Issue `service sqm-autorate start`
4. `top` shows the lua script immediately

**Expected behavior**
`sqm-autorate.lua` should be running immediately after a reboot

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: 21.02.1
 - Connection Type + Speed: Symmetric 25/25 mbps

**Comment by Fail-Safe** [comment]
This was fixed in `testing/lua-threads` 0.0.1b6 per https://github.com/Fail-Safe/sqm-autorate/issues/45.

**Comment by richb-hanover** [comment]
Yes, verified with version 0.2.1. Thanks!
