### ISSUE TITLE
[FEATURE] exchangable ratecontrol

### ISSUE THREAD

**Issue by moeller0** [Fail-Safe/sqm-autorate#64]
We have been discussing the option of having selectable ratecontrol modules, how shall we do this in a way that the ratecontrol can be changed from the config file?

Just multiplexing different behavior into the existing ratecontrol module would work but feels a bit unclean. Especially since I want to drive ratecontrol not (just) by a timer but by each received and baselined packet (basically have the baseline calculator write a control lane/linda to trigger the next ratecontrol cycle).

**Comment by Lochnair** [comment]
Being more easily able to swap out parts of the code is a big motivation behind #61

I'll have to think about it a bit, but it should be reasonably easy to extend that to let us have different ratecontrol modules to choose from

**Comment by moeller0** [comment]
> Being more easily able to swap out parts of the code is a big motivation behind #61
Thanks!
I saw that, and thought now is the time to bring this up since major surgery is happening so a small change can be shoed in hopefully relatively easy.

**Comment by moeller0** [comment]
While pondering this, it seems that selectable ratecontrol might not be needed.
