### ISSUE TITLE
Ingress autorate does not work when using br-lan as the download_interface

### ISSUE THREAD

**Issue by jeverley** [Fail-Safe/sqm-autorate#94]
**Script Version**
v0.4.3

**Describe the bug**
The service incorrectly reads the upload rate rather than download rate when SQM wan ingress is configured on device br-lan 
This setup can be used to facilitate DSCP based ingress classification on routers without a wifi interface, the setup is similar to that used for ifb/veth devices which are currently handled by the service by reading device tx_bytes.

**To Reproduce**
Specify br-lan as the download_interface in /etc/config/sqm-autorate

**Expected behavior**
The service derives upload rates by reading the br-lan tx or upload device rx - the former has the disadvantage of including non-wan traffic in the rate measurements.

Below is the temporary local change I've made for the purpose of testing the service.

```
if dl_if:find("^ifb.+") or dl_if:find("^veth.+") then
    rx_bytes_path = "/sys/class/net/" .. dl_if .. "/statistics/tx_bytes"
elseif dl_if == "br-lan" then
    rx_bytes_path = "/sys/class/net/" .. ul_if .. "/statistics/rx_bytes"
else
    rx_bytes_path = "/sys/class/net/" .. dl_if .. "/statistics/rx_bytes"
end
```

**Comment by Fail-Safe** [comment]
@jeverley Could you please take a look at #96 and let me know if that adequately addresses the issue for you?
