### ISSUE TITLE
Service crash when a wan interface is brought up/down (regardless of log level)

### ISSUE THREAD

**Issue by jeverley** [Fail-Safe/sqm-autorate#99]
**Script Version**
v0.4.3

**Describe the bug**

In support of discussion around multi interface support I've been testing current service behaviour when interfaces are brought up/down.

I've found that when a wan device interface is brought up or down it results in a crash due to the string.format() function encountering a nil as one of its inputs (the function doesn't support converting nils).

```
Something went wrong in the regulator thread
/usr/lib/sqm-autorate/sqm-autorate.lua:833: bad argument #2 to 'format' (string expected, got nil)
```

```
if rx_load and tx_load and up_del_stat and down_del_stat then
    logger(loglevel.DEBUG,
        string.format("%d,%d,%f,%f,%f,%f,%d,%d\n", lastchg_s, lastchg_ns, rx_load, tx_load,
        
            down_del_stat, up_del_stat, cur_dl_rate, cur_ul_rat
    -- output to log file before doing delta on the time
    csv_fd:write(string.format("%d,%d,%f,%f,%f,%f,%d,%d\n", lastchg_s, lastchg_ns, rx_load, tx_load,
        down_del_stat, up_del_stat, cur_dl_rate, cur_ul_rate))
else
    logger(loglevel.DEBUG,
        string.format(
            "Missing value error: rx_load = %s | tx_load = %s | down_del_stat = %s | up_del_stat = %s",
            rx_load, tx_load, down_del_stat, up_del_stat))
end
```

Amending line the string.format line to read as below avoids this error and the service can continue execution:

```
logger(loglevel.DEBUG,
    string.format(
        "Missing value error: rx_load = %s | tx_load = %s | down_del_stat = %s | up_del_stat = %s",
        tostring(rx_load), tostring(tx_load), tostring(down_del_stat), tostring(up_del_stat)))
```

**To Reproduce**
Whilst the service is running execute either the ifup or ifdown command, e.g. ```ifup wwan``` / ```ifdown wwan```

**Comment by Fail-Safe** [comment]
Fixed in `testing/lua-threads` per dc7c36c9d4992d99b4f1cbb3d603bf6383656814.
